### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by USTC-wlsong** [ubc-vision/COTR#9]
Thank you very much for your open source code！ 
When I run "python demo_single_pair.py --load_weights="default"", the bug  show. Could you give me some debugging advice?
![image](https://user-images.githubusercontent.com/73636505/132695732-34d7049b-b15d-4c5d-b008-7e8fbd182882.png)

**Comment by TheRealPoseidon** [comment]
> Thank you very much for your open source code！ When I run "python demo_single_pair.py --load_weights="default"", the bug show. Could you give me some debugging advice? ![image](https://user-images.githubusercontent.com/73636505/132695732-34d7049b-b15d-4c5d-b008-7e8fbd182882.png)

Hi, I'm facing same problem.  How did you solve it?

**Comment by jiangwei221** [comment]
Hi, it seems that you don't have wispy installed in the environment. You can try to install it and try again.

**Comment by TheRealPoseidon** [comment]
> Hi, it seems that you don't have vispy installed in the environment. You can try to install it and try again.

Thank you!

**Comment by IamMegatron2025** [comment]
@jiangwei221 @TheRealPoseidon  hello, after I installed the `vispy`, it still shows the error:

```
Traceback (most recent call last):
  File "demo_single_pair.py", line 71, in <module>
    main(opt)
  File "demo_single_pair.py", line 46, in main
    dense = triangulate_corr(corrs, img_a.shape, img_b.shape)
TypeError: 'NoneType' object is not callable

```
What else should I do to fix this?
